---
title: "Bootstrap ITT with 3-month washout"
author: "Khuong Quynh Long"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    highlight: pygments
    number_sections: yes
    theme: flatly
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(magrittr)
```


```{r}
df <- readRDS("statin_clean_3m.rds")
```

# Setup data


```{r}
#===============================================================================
df %<>% mutate(visit_month2 = visit_month*visit_month)

uniq_id <- unique(df$id)

uniq_id0 <- unique(df$id[df$statin_yn_b == 0])
uniq_id1 <- unique(df$id[df$statin_yn_b == 1])

n0 <- length(unique(df$id[df$statin_yn_b == 0]))
n1 <- length(unique(df$id[df$statin_yn_b == 1]))

n <- length(unique(df$id))
# m <- round(max(df$visit_month))
m <- 24


n; n1; n0

# Check
n == n0 + n1
```


# Doing boostrap

```{r}
B <- 1000

# Set up dataframe to store all estimates across different iterations
tab_ITT_boot <- data.frame(
  visit_month = NA,
  Placebo = NA,
  Treated = NA,
  RD = NA, 
  logRatio = NA,
  CIR = NA,
  cHR = NA
)


set.seed(12345)
for (i in seq(B)) {
  
  # Sampling ID
  df_boot0 <- data.frame(id = sample(uniq_id0, n0, replace = TRUE))
  df_boot1 <- data.frame(id = sample(uniq_id1, n1, replace = TRUE))
  df_boot <- rbind(df_boot0, df_boot1)

  # Merge with original data with bootstrap ID
  df_boot %<>% left_join(df, by = "id")
  
  df_boot %<>% arrange(id, date_in)
  
  # Take baseline data frame
  df_boot_bs <- df_boot %>% filter(visit_n == 1)
  
  #----- Data processing: interaction terms
  df_boot %<>% mutate(
    statin_init_t = statin_yn_b*visit_month,
    statin_init_t2 = statin_yn_b*visit_month2
  )
  
  #----- Step 1. Fit a pooled logistic  regression model with interaction terms between 
  adj_plr_ITT <- glm(ICH ~ visit_month + visit_month2 + statin_yn_b + 
                        statin_init_t + statin_init_t2 + age_b + sex + hyper_b + 
                        diabetes_b + insulin_b + nsaids_b +  COPD_b + corticoids_b + 
                        depress_b + cancer_b + aneurysmis_b + osteoporosis_b,
                        data = df, family=binomial())
  
  gc()
  #----- Step 2. Create simulated data where everyone is treated
  tr_ITT_boot <- df_boot_bs[rep(1:n, each = m),]
  tr_ITT_boot$visit_month <- rep(0:(m-1), times=n)
  tr_ITT_boot %<>%
    mutate(
      # recreate squared visit term
      visit_month2 = visit_month*visit_month, 
      # Set the treatment assignment to '1' for each individual and
      statin_yn_b = 1, 
      # recreate the interaction terms
      statin_init_t = statin_yn_b*visit_month,
      statin_init_t2 = statin_yn_b*visit_month2
    )
  
  # 'predict' returns predicted "density" of risk at each time
  tr_ITT_boot$p <- 1 - predict(adj_plr_ITT_boot, newdata = tr_ITT_boot, type='response')
  tr_ITT_boot <- tr_ITT_boot[, c('id', 'p', 'statin_yn_b', 'visit_month')]
  
  # Calculate survival by taking the cumulative product by individual
  tr_ITT_boot <- tr_ITT_boot %>%
    arrange(id, visit_month)%>%
    group_by(id) %>%
    mutate(s = cumprod(p))
  
  #----- Step 3. Create simulated data where everyone receives placebo
  ct_ITT_boot <- df_boot_bs[rep(1:n, each = m),]
  ct_ITT_boot$visit_month <- rep(0:(m-1), times=n)
  ct_ITT_boot %<>%
    mutate(
      # recreate squared visit term
      visit_month2 = visit_month*visit_month, 
      # Set the treatment assignment to '1' for each individual and
      statin_yn_b = 0, 
      # recreate the interaction terms
      statin_init_t = statin_yn_b*visit_month,
      statin_init_t2 = statin_yn_b*visit_month2
    )
  
  # 'predict' returns predicted "density" of risk at each time
  ct_ITT_boot$p <- 1 - predict(adj_plr_ITT_boot, newdata=ct_ITT_boot, type='response')
  ct_ITT_boot <- ct_ITT_boot[, c('id', 'p', 'statin_yn_b', 'visit_month')]
  
  rm(adj_plr_ITT_boot)
  
  # Calculate survival by taking the cumulative product by individual
  ct_ITT_boot <- ct_ITT_boot %>%
    arrange(id, visit_month)%>%
    group_by(id) %>%
    mutate(s = cumprod(p))
  
  #----- Step 4. Calculate standardized survival at each time
  both_ITT_boot <- bind_rows(tr_ITT_boot, ct_ITT_boot)
  both_ITT_boot <- both_ITT_boot[, c('s', 'statin_yn_b', 'visit_month')]
  
  rm(tr_ITT_boot)
  rm(ct_ITT_boot)
  

  # Calculate the mean survival at each visit within each treatment arm
  results_ITT_boot <- both_ITT_boot %>%
    group_by(visit_month, statin_yn_b) %>%
    summarise(mean_survival = mean(s)) %>% ungroup()
  
  rm(both_ITT_boot)
  
  # Edit results data frame to reflect that our estimates are for the END of the interval [t, t+1)
  results_ITT_boot %<>% mutate(visit_month = visit_month + 1)
  results_ITT_boot <- bind_rows(c(visit_month = 0, statin_yn_b = 0, mean_survival =  1),
                                c(visit_month = 0, statin_yn_b = 1, mean_survival =  1),
                                results_ITT_boot)
  
  # Add a variable that treats randomization as a factor
  results_ITT_boot$init <- factor(results_ITT_boot$statin_yn_b, labels = c("Placebo", "Treated"))

  wideres_ITT_boot <- results_ITT_boot %>% pivot_wider(id_cols = visit_month, 
                                                       names_from = init, 
                                                       values_from = mean_survival)
  
  # Create summary statistics
  wideres_ITT_boot %<>%
    mutate(
      RD = (1 - Treated) - (1 - Placebo),
      logRatio = log(Treated)/log(Placebo),
      CIR = (1 - Treated)/ (1 - Placebo)
    )
  
  wideres_ITT_boot$logRatio[1] <- NA
  wideres_ITT_boot$cHR <- sapply(0:m, FUN = function(x){mean(wideres_ITT_boot$logRatio[wideres_ITT_boot$visit_month <= x], 
                                                             na.rm=T)})
  
  tab_ITT_boot <- tab_ITT_boot %>% add_row(wideres_ITT_boot)
  

   gc()
}

rm(df_boot)
rm(df_boot_bs)

saveRDS(tab_ITT_boot, "Boots_ITT_3m.rds")
```



```{r}
# RD
RD_boot_12 <- tab_ITT_boot %>% filter(visit_month == 12) %>% pull(RD)
RD_boot_24 <- tab_ITT_boot %>% filter(visit_month == 24) %>% pull(RD)

# cHR
cHR_boot_12 <- tab_ITT_boot %>% filter(visit_month == 12) %>% pull(cHR)
cHR_boot_24 <- tab_ITT_boot %>% filter(visit_month == 24) %>% pull(cHR)
```


# Summary


```{r}
#----- 12 months
# Risk difference
quantile(RD_boot_12, probs = c(0.025, 0.975))
# Hazard ratio
quantile(cHR_boot_12, probs = c(0.025, 0.975))

#----- 24 months
# Risk difference
quantile(RD_boot_24, probs = c(0.025, 0.975))
# Hazard ratio
quantile(cHR_boot_24, probs = c(0.025, 0.975))
```

# Histogram

```{r}
par(mfrow = c(2, 2))
hist(RD_boot_12)
hist(cHR_boot_12)

hist(RD_boot_24)
hist(cHR_boot_24)
par(mfrow = c(1, 1))
dev.off()
```






